AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowOrigin: "'http://localhost:8080'"
    BinaryMediaTypes:
      - image~1gif
      - image~1png
      - image~1jpeg
      - application/octet-stream
      - multipart/form-data

Resources:
  features:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: feature.all
      Layers:
        - arn:aws:lambda:us-west-2:005937143026:layer:LambdaCommonLayer:84
        - !Ref SusMapModelLayer
      Events:
        Building:
          Type: Api
          Properties:
            Path: /features
            Method: get
  SusMapModelLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: SusMapModelLayer
            Description: DB Model Defs
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs6.10
              - nodejs8.10
              - nodejs10.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
